name: 'hubspot_source'
version: '0.5.5'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  hubspot_source:
    +materialized: table
    +schema: stg_hubspot
    tmp:
      +materialized: view

vars:
  hubspot_source:
    company: "{{ source('hubspot','company') }}"
